Algoritmo "primeiro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/07/2022
Var
// Seção de Declarações das variáveis 
msg: Caractere
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 msg <- "Olá, Mundo!"
 Escreval ("Mensagem: ", msg)
 Escreva ("Me livrei da maldição!")

Fimalgoritmo