algoritmo "Maria do Carmo"
//Crie um programa que leia o nome e o salário de um funcionário,
//mostrando no final uma mensagem.
//Ex: Nome do Funcionário: Maria do Carmo
//Salário: 1850,45
//O funcionário Maria do Carmo tem um salário de R$1850,45 em Junho.
var
   Nome: Caractere
   Salario: Real
inicio
      Escreva ("Nome do funcionário: ", Nome)
      Leia (Nome)
      Leia (Salario)
      Escreva ("O funcionário ",Nome," tem um salário de R$",Salario," em Junho.")
fimalgoritmo