algoritmo "Soma"
// Desenvolva um algoritmo que leia dois números inteiros e
//mostre o somatório entre eles.
//Ex:
//Digite um valor: 8
//Digite outro valor: 5
//A soma entre 8 e 5 é igual a 13.
var
   N1, N2, S: Inteiro
inicio
      Escreva ("Digite um valor: ",N1)
      Leia (N1)
      Escreva ("Digite outro valor: ",N2)
      Leia (N2)
      S <- N1 + N2
      Escreva ("A soma entre",N1," e",N2," é igual a",S,".")

fimalgoritmo