algoritmo "Media"
// Faça um programa que leia as duas notas de um aluno em uma matéria e
// mostre na tela a sua média na disciplina.
//Ex:
//Nota 1: 4.5
//Nota 2: 8.5
//A média entre 4.5 e 8.5 é igual a 6.5
var
   N1, N2, M: Real
inicio
      Escreva ("Nota 1: ",N1)
      Leia (N1)
      Escreva ("Nota 2: ",N2)
      Leia (N2)
      M <- (N1 + N2)/2
      Escreva ("A média entre",N1," e",N2," é igual a",M,".")
fimalgoritmo